####regester user
post http://localhost:3550/user/register
Content-Type: application/json

{
    "username": "jenny",
    "email":"jenny1@thejitu.com",
    "password": "@Jenny433"
}

#####get all users

get http://localhost:3550/user
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Implbm55QHRoZWppdHUuY29tIiwiaWQiOiIxM2M0ZjdiOS0wZDlhLTQxODAtYTViZS02ZmVkZjI4YzY2NzgiLCJpYXQiOjE2OTg3NDg3NDAsImV4cCI6MTY5ODgzNTE0MH0.jZ2-LcurzlMYJNRU_cTaQdTjSFzw7LhvoZ0cYZ6YyIY


#####get one user by id
get http://localhost:3550/user/13c4f7b9-0d9a-4180-a5be-6fedf28c6678

####login user

post http://localhost:3550/user/login
Content-Type: application/json

{
    
    "email":"jenny@thejitu.com",
    "password": "@Jenny433"
}
#####update user
put http://localhost:3550/user
Content-Type: application/json

{
    "id":"018ed0d4-879b-4a48-97fa-9748c3d34b10",
    "username": "daniel",
    "email":"dan@thejitu.com"    
}

##### delete user by ID
delete http://localhost:3550/user/ec0311a5-7cb1-491f-89b2-3699b89d30c0

